// Phase 13E.5A - BUFFER PROVIDER ADAPTER (implemented, NOT exercised).
//
// Buffer is the chosen single scheduling / autopost layer for Instagram
// and TikTok. This adapter isolates every Buffer-specific detail behind
// one interface so the distribution layer never knows which provider is
// underneath (same pattern as lib/outreach/provider.js -> Instantly).
//
// VERIFIED CURRENT BUFFER FACTS (developers.buffer.com, support.buffer.com,
// checked 2026-09-07 - see docs/social-distribution.md):
//   * Public API is CURRENT (GraphQL, developers.buffer.com). API-KEY
//     auth; the key is generated by the account owner at
//     https://publish.buffer.com/settings/api  (Bearer header).
//   * Platforms include Instagram AND TikTok.
//   * `channels(...)` lists the org's connected channels + ids.
//   * `createPost(input: CreatePostInput!)` fields used here:
//        channelId, text, assets[] (image|video, ordered),
//        dueAt (schedule), saveToDraft, schedulingType (automatic|notification),
//        metadata (service-specific: instagram.firstComment, postType reel).
//   * Instagram: FB Page link NOT required to publish (only for Analyze /
//     location tagging). Business/Creator account required for AUTOMATIC
//     publishing; Personal = notification only. Carousel <=10 images.
//     First comment only on auto-publish. Reels 3s-15min, 4:5..9:16, <=1920w.
//   * TikTok: requires a TikTok BUSINESS account; automatic publish uses
//     ORIGINAL AUDIO only (no trending sounds via API).
//   * Rate limits are per-client rolling windows (100/15min, 250-500/24h,
//     3k-15k/30d), HTTP 429 + Retry-After.
//   * No webhook for post status in the public API today -> status is
//     confirmed by POLLING `post(input:{id})` in getPostStatus().
//
// SAFETY: with no BUFFER_ACCESS_TOKEN in the environment, getSocialProvider()
// returns the null provider and this code never runs. Even configured, a
// call only happens from scripts/socialPublish.mjs `send`, which itself
// hard-fails unless every gate in lib/social/distribution/gates.mjs passes.

const BUFFER_GRAPHQL = "https://graph.buffer.com/"; // GraphQL endpoint (developers.buffer.com)

async function bufferGraphQL(apiKey, query, variables) {
  const res = await fetch(BUFFER_GRAPHQL, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ query, variables }),
    signal: AbortSignal.timeout(30000),
  });
  const retryAfter = res.headers.get("retry-after");
  const rate = res.headers.get("ratelimit");
  if (res.status === 429) {
    return { ok: false, reason: "buffer_rate_limited", detail: `retry-after=${retryAfter ?? "?"} ${rate ?? ""}`.trim() };
  }
  let json = null;
  try {
    json = await res.json();
  } catch {
    return { ok: false, reason: `buffer_http_${res.status}`, detail: "non-JSON response" };
  }
  if (!res.ok || json.errors?.length) {
    const msg = json.errors?.map((e) => e.message).join("; ") || `HTTP ${res.status}`;
    return { ok: false, reason: `buffer_error`, detail: msg.slice(0, 400) };
  }
  return { ok: true, data: json.data, rate: { policy: rate, retryAfter } };
}

export function bufferProvider(env = process.env) {
  const apiKey = String(env.BUFFER_ACCESS_TOKEN ?? "").trim() || null;

  return {
    name: "buffer",
    isConfigured: () => Boolean(apiKey),

    // List the connected channels so the owner can map instagram_main /
    // tiktok_main -> a stable Buffer channel id (channels.json).
    async listChannels() {
      if (!apiKey) return { ok: false, reason: "buffer_not_configured" };
      const q = `query { channels(input: { }) { id name service serviceType type locked } }`;
      const r = await bufferGraphQL(apiKey, q, {});
      if (!r.ok) return r;
      const channels = (r.data?.channels ?? []).map((c) => ({
        id: c.id,
        name: c.name,
        service: c.service, // "instagram" | "tiktok" | ...
        type: c.serviceType ?? c.type ?? null,
        locked: Boolean(c.locked),
      }));
      return { ok: true, channels };
    },

    // Create ONE post/update. msg:
    //   { channelId, text, assets:[{type:"image"|"video", url, thumbnailUrl?, altText?}],
    //     dueAt:string|null, saveToDraft:boolean, schedulingType:"automatic"|"notification",
    //     postType:"post"|"reel", firstComment:string|null }
    // Returns { accepted, id?, reason?, detail? }. A created post is
    // ACCEPTED into Buffer's queue - NOT proof it published.
    async createPost(msg) {
      if (!apiKey) return { accepted: false, reason: "buffer_not_configured" };
      const mutation = `
        mutation CreatePost($input: CreatePostInput!) {
          createPost(input: $input) { id status dueAt }
        }`;
      const input = {
        channelId: msg.channelId,
        text: msg.text,
        assets: (msg.assets ?? []).map((a, i) => ({
          type: a.type,
          url: a.url,
          thumbnailUrl: a.thumbnailUrl ?? null,
          altText: a.altText ?? null,
          order: i,
        })),
        schedulingType: msg.schedulingType ?? "automatic",
        saveToDraft: Boolean(msg.saveToDraft),
        ...(msg.dueAt ? { dueAt: msg.dueAt, mode: "customScheduled" } : { mode: "addToQueue" }),
        metadata: {
          ...(msg.postType ? { postType: msg.postType } : {}),
          ...(msg.firstComment ? { instagram: { firstComment: msg.firstComment } } : {}),
        },
      };
      const r = await bufferGraphQL(apiKey, mutation, { input });
      if (!r.ok) return { accepted: false, reason: r.reason, detail: r.detail };
      const post = r.data?.createPost;
      if (!post?.id) return { accepted: false, reason: "buffer_no_post_id", detail: JSON.stringify(r.data).slice(0, 300) };
      return { accepted: true, id: post.id, statusRaw: post.status ?? null, dueAt: post.dueAt ?? null };
    },

    // Poll one post and normalise "did it actually publish?".
    //   -> { ok, published, publishedAt, failed, failReason?, statusRaw }
    // Buffer post statuses: draft | buffer(queued) | sent(published) |
    // failed | paused. Only "sent" WITH a sentAt is real publish evidence.
    async getPostStatus(id) {
      if (!apiKey) return { ok: false, reason: "buffer_not_configured" };
      const q = `query Post($input: PostInput!) { post(input: $input) { id status sentAt dueAt error } }`;
      const r = await bufferGraphQL(apiKey, q, { input: { id } });
      if (!r.ok) return { ok: false, reason: r.reason, detail: r.detail };
      const p = r.data?.post;
      if (!p) return { ok: false, reason: "buffer_post_not_found" };
      const status = String(p.status ?? "").toLowerCase();
      const published = status === "sent" && Boolean(p.sentAt);
      const failed = status === "failed";
      return {
        ok: true,
        published,
        publishedAt: published ? p.sentAt : null,
        failed,
        failReason: failed ? String(p.error ?? "buffer reported failed") : undefined,
        statusRaw: p.status ?? null,
      };
    },
  };
}
