// GENERATED by scripts/seo/generateReprintPrintings.mjs - do not hand-edit.
// Re-run that script when a reprint set is added or renumbered.
//
// Reprint sets keep the ORIGINAL card's number (Celebrations: Classic
// Collection carries Blastoise at 2/102, the Base Set number). That makes
// the number useless for telling an original from a reprint - but only
// for the numbers the reprint set actually uses. These lists are what let
// lib/dealQuality separate a real ambiguity from a seller stuffing "30th"
// into the title of a genuine vintage card.
//
// Generated 2026-09-21 from card_catalog.
// Keys are quoted: "30th" is not a valid bare identifier.
const REPRINT_CARDS = {
  "30th": {
    "21/128": [
      "greninjaex021128"
    ],
    "71/128": [
      "sylveonex071128"
    ],
    "69/128": [
      "espeon"
    ],
    "91/128": [
      "umbreon"
    ],
    "36/128": [
      "pikachu036128"
    ],
    "37/128": [
      "pikachu037128"
    ],
    "47/128": [
      "pikachu047128"
    ],
    "131/128": [
      "lapras131128"
    ],
    "136/128": [
      "drifloon136128"
    ],
    "138/128": [
      "lycanroc138128"
    ],
    "145/128": [
      "hisuianzorua145128"
    ],
    "157/128": [
      "mewtwoex157128"
    ],
    "158/128": [
      "mewex158128"
    ],
    "13/128": [
      "victini"
    ],
    "57/128": [
      "zeraora"
    ],
    "117/128": [
      "eevee117128"
    ],
    "118/128": [
      "eevee118128"
    ],
    "70/128": [
      "espeonex"
    ],
    "92/128": [
      "umbreonex"
    ],
    "23/128": [
      "pikachu023128"
    ],
    "25/128": [
      "pikachu025128"
    ],
    "26/128": [
      "pikachu026128"
    ],
    "28/128": [
      "pikachu028128"
    ],
    "30/128": [
      "pikachu030128"
    ],
    "32/128": [
      "pikachu032128"
    ],
    "33/128": [
      "pikachu033128"
    ],
    "34/128": [
      "pikachu034128"
    ],
    "38/128": [
      "pikachu038128"
    ],
    "39/128": [
      "pikachu039128"
    ],
    "40/128": [
      "pikachu040128"
    ],
    "41/128": [
      "pikachu041128"
    ],
    "42/128": [
      "pikachu042128"
    ],
    "43/128": [
      "pikachu043128"
    ],
    "44/128": [
      "pikachu044128"
    ],
    "49/128": [
      "pikachu049128"
    ],
    "50/128": [
      "pikachu050128"
    ],
    "53/128": [
      "pikachuex053128"
    ],
    "54/128": [
      "pikachuex054128"
    ],
    "149/128": [
      "pikachuex149128"
    ],
    "150/128": [
      "pikachuex150128"
    ],
    "113/128": [
      "meowth113128"
    ],
    "116/128": [
      "eevee116128"
    ],
    "144/128": [
      "meowth144128"
    ],
    "89/128": [
      "alolanmeowth089128"
    ],
    "139/128": [
      "alolanmeowth139128"
    ],
    "4/102": [
      "charizard"
    ],
    "33/181": [
      "pikachuzekromgx"
    ],
    "149/147": [
      "lugia"
    ],
    "5/109": [
      "delcatty"
    ],
    "11/113": [
      "metagrossdeltaspecies"
    ],
    "11/101": [
      "genesectexteamplasma"
    ],
    "18/132": [
      "misty"
    ],
    "19/109": [
      "darktyranitar"
    ],
    "25/111": [
      "sneasel"
    ],
    "41/122": [
      "greninjabreak"
    ],
    "43/146": [
      "uxie"
    ],
    "47/127": [
      "crobatg"
    ],
    "50/185": [
      "raikou"
    ],
    "57/111": [
      "buzzwolegx"
    ],
    "58/102": [
      "pikachu"
    ],
    "69/132": [
      "erikasjigglypuff"
    ],
    "85/124": [
      "rayquazaex"
    ],
    "89/149": [
      "solgaleogx"
    ],
    "94/102": [
      "gengarprime"
    ],
    "99/102": [
      "darkraicresselialegendtop"
    ],
    "100/102": [
      "darkraicresselialegendbottom"
    ],
    "101/101": [
      "n"
    ],
    "106/106": [
      "palkialvx"
    ],
    "106/160": [
      "mgardevoirex"
    ],
    "106/105": [
      "shiningcelebi"
    ],
    "108/115": [
      "scizorex"
    ],
    "114/264": [
      "mewvmax"
    ],
    "123/172": [
      "arceusvstar"
    ],
    "138/202": [
      "zacianv"
    ],
    "203/193": [
      "magikarp"
    ],
    "129/128": [
      "alolanexeggutor129128"
    ],
    "130/128": [
      "moltres130128"
    ],
    "132/128": [
      "articuno132128"
    ],
    "133/128": [
      "zapdos133128"
    ],
    "134/128": [
      "toxtricity134128"
    ],
    "135/128": [
      "morpeko135128"
    ],
    "137/128": [
      "chandelure137128"
    ],
    "140/128": [
      "scraggy140128"
    ],
    "141/128": [
      "galarianmeowth141128"
    ],
    "142/128": [
      "gholdengo142128"
    ],
    "146/128": [
      "maushold146128"
    ],
    "147/128": [
      "fuecocoex147128"
    ],
    "148/128": [
      "greninjaex148128"
    ],
    "153/128": [
      "sylveonex153128"
    ],
    "155/128": [
      "jirachiex155128"
    ],
    "156/128": [
      "salamenceex156128"
    ],
    "24/128": [
      "pikachu024128"
    ],
    "27/128": [
      "pikachu027128"
    ],
    "29/128": [
      "pikachu029128"
    ],
    "31/128": [
      "pikachu031128"
    ],
    "35/128": [
      "pikachu035128"
    ],
    "45/128": [
      "pikachu045128"
    ],
    "46/128": [
      "pikachu046128"
    ],
    "48/128": [
      "pikachu048128"
    ],
    "51/128": [
      "pikachu051128"
    ],
    "52/128": [
      "pikachu052128"
    ],
    "1/128": [
      "exeggcute"
    ],
    "2/128": [
      "alolanexeggutor002128"
    ],
    "3/128": [
      "volbeat"
    ],
    "4/128": [
      "illumise"
    ],
    "5/128": [
      "tropius"
    ],
    "6/128": [
      "cherubi"
    ],
    "7/128": [
      "cherrim"
    ],
    "8/128": [
      "vivillon"
    ],
    "9/128": [
      "vulpix"
    ],
    "10/128": [
      "ninetales"
    ],
    "11/128": [
      "moltres011128"
    ],
    "12/128": [
      "hooh"
    ],
    "14/128": [
      "reshiram"
    ],
    "15/128": [
      "fuecocoex015128"
    ],
    "16/128": [
      "slowpoke"
    ],
    "17/128": [
      "lapras017128"
    ],
    "18/128": [
      "articuno018128"
    ],
    "19/128": [
      "kyogre"
    ],
    "20/128": [
      "palkia"
    ],
    "22/128": [
      "wishiwashi"
    ],
    "55/128": [
      "zapdos055128"
    ],
    "56/128": [
      "zekrom"
    ],
    "58/128": [
      "toxel"
    ],
    "59/128": [
      "toxtricity059128"
    ],
    "60/128": [
      "toxtricity060128"
    ],
    "61/128": [
      "morpeko061128"
    ],
    "62/128": [
      "miraidon"
    ],
    "63/128": [
      "mewtwo"
    ],
    "64/128": [
      "mewtwoex064128"
    ],
    "65/128": [
      "mew"
    ],
    "66/128": [
      "mewex066128"
    ],
    "67/128": [
      "marill"
    ],
    "68/128": [
      "azumarill"
    ],
    "72/128": [
      "unown"
    ],
    "73/128": [
      "drifloon073128"
    ],
    "74/128": [
      "cresselia"
    ],
    "75/128": [
      "chandelure075128"
    ],
    "76/128": [
      "xerneas"
    ],
    "77/128": [
      "comfey"
    ],
    "78/128": [
      "cosmog"
    ],
    "79/128": [
      "cosmoem"
    ],
    "80/128": [
      "lunala"
    ],
    "81/128": [
      "gimmighoul"
    ],
    "82/128": [
      "groudon"
    ],
    "83/128": [
      "lucario"
    ],
    "84/128": [
      "seismitoad"
    ],
    "85/128": [
      "lycanroc085128"
    ],
    "86/128": [
      "koraidon"
    ],
    "87/128": [
      "nidoranf"
    ],
    "88/128": [
      "nidorina"
    ],
    "90/128": [
      "gengarex090128"
    ],
    "93/128": [
      "murkrow"
    ],
    "94/128": [
      "scraggy094128"
    ],
    "95/128": [
      "zorua"
    ],
    "96/128": [
      "zoroark"
    ],
    "97/128": [
      "deino"
    ],
    "98/128": [
      "zweilous"
    ],
    "99/128": [
      "hydreigon"
    ],
    "100/128": [
      "yveltal"
    ],
    "101/128": [
      "galarianmeowth101128"
    ],
    "102/128": [
      "jirachiex102128"
    ],
    "103/128": [
      "dialga"
    ],
    "104/128": [
      "ferrothorn"
    ],
    "105/128": [
      "solgaleo"
    ],
    "106/128": [
      "zacian"
    ],
    "107/128": [
      "zamazenta"
    ],
    "108/128": [
      "gholdengo108128"
    ],
    "109/128": [
      "salamenceex109128"
    ],
    "110/128": [
      "jangmoo"
    ],
    "111/128": [
      "hakamoo"
    ],
    "112/128": [
      "kommoo112128"
    ],
    "114/128": [
      "kangaskhan"
    ],
    "115/128": [
      "ditto"
    ],
    "119/128": [
      "snorlax"
    ],
    "120/128": [
      "igglybuff"
    ],
    "121/128": [
      "lugia"
    ],
    "122/128": [
      "hisuianzorua122128"
    ],
    "123/128": [
      "hisuianzoroark"
    ],
    "124/128": [
      "minior"
    ],
    "125/128": [
      "maushold125128"
    ],
    "126/128": [
      "pokepad"
    ],
    "127/128": [
      "switch"
    ],
    "128/128": [
      "ultraball"
    ],
    "151/128": [
      "mewtwoex151128"
    ],
    "152/128": [
      "mewex152128"
    ],
    "R/RGB": [
      "mewrrgb"
    ],
    "G/RGB": [
      "mewgrgb"
    ],
    "B/RGB": [
      "mewbrgb"
    ],
    "154/128": [
      "gengarex154128"
    ],
    "143/128": [
      "kommoo143128"
    ]
  },
  "celebrations": {
    "24/25": [
      "professorsresearchprofessoroakfullart"
    ],
    "8/82": [
      "darkgyarados"
    ],
    "25/25": [
      "mewsecret"
    ],
    "20/25": [
      "dialga"
    ],
    "14/25": [
      "cosmoem"
    ],
    "3/25": [
      "kyogre"
    ],
    "18/25": [
      "zamazentav"
    ],
    "1/25": [
      "hooh"
    ],
    "2/25": [
      "reshiram"
    ],
    "4/25": [
      "palkia"
    ],
    "5/25": [
      "pikachu"
    ],
    "6/25": [
      "flyingpikachuv"
    ],
    "7/25": [
      "flyingpikachuvmax"
    ],
    "8/25": [
      "surfingpikachuv"
    ],
    "9/25": [
      "surfingpikachuvmax"
    ],
    "10/25": [
      "zekrom"
    ],
    "11/25": [
      "mew"
    ],
    "12/25": [
      "xerneas"
    ],
    "13/25": [
      "cosmog"
    ],
    "15/25": [
      "lunala"
    ],
    "16/25": [
      "zacianv"
    ],
    "17/25": [
      "groudon"
    ],
    "19/25": [
      "yveltal"
    ],
    "21/25": [
      "solgaleo"
    ],
    "22/25": [
      "lugia"
    ],
    "23/25": [
      "professorsresearchprofessoroak"
    ],
    "2/102": [
      "blastoise"
    ],
    "4/102": [
      "charizard"
    ],
    "15/102": [
      "venusaur"
    ],
    "73/102": [
      "imposterprofessoroak"
    ],
    "15/82": [
      "herecomesteamrocket"
    ],
    "15/132": [
      "rocketszapdos"
    ],
    "24/53": [
      "spikachu"
    ],
    "20/111": [
      "cleffa"
    ],
    "66/64": [
      "shiningmagikarp"
    ],
    "9/95": [
      "teammagmasgroudon"
    ],
    "86/109": [
      "rocketsadmin"
    ],
    "88/92": [
      "mewex"
    ],
    "93/101": [
      "gardevoirexdeltaspecies"
    ],
    "17/17": [
      "umbreonstar"
    ],
    "15/106": [
      "claydol"
    ],
    "109/111": [
      "luxraygllvx"
    ],
    "145/147": [
      "garchompclvx"
    ],
    "107/123": [
      "donphanprime"
    ],
    "113/114": [
      "reshiram"
    ],
    "114/114": [
      "zekrom"
    ],
    "54/99": [
      "mewtwoex"
    ],
    "97/146": [
      "xerneasex"
    ],
    "76/108": [
      "mrayquazaex"
    ],
    "60/145": [
      "tapulelegx"
    ],
    "14/83": [
      "ponyta"
    ]
  }
};

// Letters and digits only, so "Mewtwo-EX" and "Mewtwo EX" agree.
function normaliseCardName(value) {
  return String(value ?? "").toLowerCase().replace(/[^a-z0-9]+/g, "");
}

// "12/113" -> "12/113" with leading zeros stripped from each part.
function normaliseCardNumber(value) {
  return String(value ?? "")
    .split("/")
    .map((part) => part.trim().replace(/^0+(?=\d)/, ""))
    .join("/");
}

// Does this reprint family contain THIS card at THIS number? Both must
// match: the family having some card at 18/132 says nothing about a
// listing for Misty 18/132.
// Names are compared by PREFIX in either direction, because a deal row
// carries "Metagross" where the catalogue carries "Metagross Delta
// Species". Exact equality would miss every such pair and report a real
// ambiguity as keyword stuffing.
function reprintFamilyHasCard(family, name, number) {
  const index = REPRINT_CARDS[family];
  if (!index) return false;
  const n = normaliseCardNumber(number);
  const nm = normaliseCardName(name);
  if (n === "" || nm === "") return false;
  const names = index[n];
  if (!names) return false;
  return names.some((catalogueName) => catalogueName.startsWith(nm) || nm.startsWith(catalogueName));
}

module.exports = { REPRINT_CARDS, normaliseCardName, normaliseCardNumber, reprintFamilyHasCard };
