// AUTO-GENERATED by scripts/generateSetImages.js - do not edit by hand.
// Set name -> pokemontcg.io (images.scrydex.com) logo/symbol image URLs.
// 161 matched, 46 without an image
// (rendered as set-name text). Regenerate when new sets appear.

const SET_IMAGES = {
  "Aquapolis": {
    "logo": "https://images.pokemontcg.io/ecard2/logo.png",
    "symbol": "https://images.pokemontcg.io/ecard2/symbol.png"
  },
  "Arceus": {
    "logo": "https://images.pokemontcg.io/pl4/logo.png",
    "symbol": "https://images.pokemontcg.io/pl4/symbol.png"
  },
  "Base Set": {
    "logo": "https://images.pokemontcg.io/base1/logo.png",
    "symbol": "https://images.pokemontcg.io/base1/symbol.png"
  },
  "Base Set (Shadowless)": {
    "logo": "https://images.pokemontcg.io/base1/logo.png",
    "symbol": "https://images.pokemontcg.io/base1/symbol.png"
  },
  "Base Set 2": {
    "logo": "https://images.pokemontcg.io/base4/logo.png",
    "symbol": "https://images.pokemontcg.io/base4/symbol.png"
  },
  "Black and White": {
    "logo": "https://images.pokemontcg.io/bw1/logo.png",
    "symbol": "https://images.pokemontcg.io/bw1/symbol.png"
  },
  "Black and White Promos": {
    "logo": "https://images.pokemontcg.io/swshp/logo.png",
    "symbol": "https://images.pokemontcg.io/swshp/symbol.png"
  },
  "Boundaries Crossed": {
    "logo": "https://images.pokemontcg.io/bw7/logo.png",
    "symbol": "https://images.pokemontcg.io/bw7/symbol.png"
  },
  "Call of Legends": {
    "logo": "https://images.pokemontcg.io/col1/logo.png",
    "symbol": "https://images.pokemontcg.io/col1/symbol.png"
  },
  "Celebrations": {
    "logo": "https://images.pokemontcg.io/cel25/logo.png",
    "symbol": "https://images.pokemontcg.io/cel25/symbol.png"
  },
  "Celebrations: Classic Collection": {
    "logo": "https://images.pokemontcg.io/cel25c/logo.png",
    "symbol": "https://images.pokemontcg.io/cel25c/symbol.png"
  },
  "Champion's Path": {
    "logo": "https://images.pokemontcg.io/swsh35/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh35/symbol.png"
  },
  "Dark Explorers": {
    "logo": "https://images.pokemontcg.io/bw5/logo.png",
    "symbol": "https://images.pokemontcg.io/bw5/symbol.png"
  },
  "Detective Pikachu": {
    "logo": "https://images.pokemontcg.io/det1/logo.png",
    "symbol": "https://images.pokemontcg.io/det1/symbol.png"
  },
  "Diamond and Pearl": {
    "logo": "https://images.pokemontcg.io/dp1/logo.png",
    "symbol": "https://images.pokemontcg.io/dp1/symbol.png"
  },
  "Diamond and Pearl Promos": {
    "logo": "https://images.pokemontcg.io/swshp/logo.png",
    "symbol": "https://images.pokemontcg.io/swshp/symbol.png"
  },
  "Double Crisis": {
    "logo": "https://images.pokemontcg.io/dc1/logo.png",
    "symbol": "https://images.pokemontcg.io/dc1/symbol.png"
  },
  "Dragon Majesty": {
    "logo": "https://images.pokemontcg.io/sm75/logo.png",
    "symbol": "https://images.pokemontcg.io/sm75/symbol.png"
  },
  "Dragon Vault": {
    "logo": "https://images.pokemontcg.io/dv1/logo.png",
    "symbol": "https://images.pokemontcg.io/dv1/symbol.png"
  },
  "Dragons Exalted": {
    "logo": "https://images.pokemontcg.io/bw6/logo.png",
    "symbol": "https://images.pokemontcg.io/bw6/symbol.png"
  },
  "EX Crystal Guardians": {
    "logo": "https://images.pokemontcg.io/ex14/logo.png",
    "symbol": "https://images.pokemontcg.io/ex14/symbol.png"
  },
  "EX Delta Species": {
    "logo": "https://images.pokemontcg.io/ex11/logo.png",
    "symbol": "https://images.pokemontcg.io/ex11/symbol.png"
  },
  "EX Deoxys": {
    "logo": "https://images.pokemontcg.io/ex8/logo.png",
    "symbol": "https://images.pokemontcg.io/ex8/symbol.png"
  },
  "EX Dragon": {
    "logo": "https://images.pokemontcg.io/ex3/logo.png",
    "symbol": "https://images.pokemontcg.io/ex3/symbol.png"
  },
  "EX Dragon Frontiers": {
    "logo": "https://images.pokemontcg.io/ex15/logo.png",
    "symbol": "https://images.pokemontcg.io/ex15/symbol.png"
  },
  "EX Emerald": {
    "logo": "https://images.pokemontcg.io/ex9/logo.png",
    "symbol": "https://images.pokemontcg.io/ex9/symbol.png"
  },
  "EX FireRed & LeafGreen": {
    "logo": "https://images.pokemontcg.io/ex6/logo.png",
    "symbol": "https://images.pokemontcg.io/ex6/symbol.png"
  },
  "EX Hidden Legends": {
    "logo": "https://images.pokemontcg.io/ex5/logo.png",
    "symbol": "https://images.pokemontcg.io/ex5/symbol.png"
  },
  "EX Holon Phantoms": {
    "logo": "https://images.pokemontcg.io/ex13/logo.png",
    "symbol": "https://images.pokemontcg.io/ex13/symbol.png"
  },
  "EX Legend Maker": {
    "logo": "https://images.pokemontcg.io/ex12/logo.png",
    "symbol": "https://images.pokemontcg.io/ex12/symbol.png"
  },
  "EX Power Keepers": {
    "logo": "https://images.pokemontcg.io/ex16/logo.png",
    "symbol": "https://images.pokemontcg.io/ex16/symbol.png"
  },
  "EX Ruby and Sapphire": {
    "logo": "https://images.pokemontcg.io/ex1/logo.png",
    "symbol": "https://images.pokemontcg.io/ex1/symbol.png"
  },
  "EX Sandstorm": {
    "logo": "https://images.pokemontcg.io/ex2/logo.png",
    "symbol": "https://images.pokemontcg.io/ex2/symbol.png"
  },
  "EX Team Magma vs Team Aqua": {
    "logo": "https://images.pokemontcg.io/ex4/logo.png",
    "symbol": "https://images.pokemontcg.io/ex4/symbol.png"
  },
  "EX Team Rocket Returns": {
    "logo": "https://images.pokemontcg.io/ex7/logo.png",
    "symbol": "https://images.pokemontcg.io/ex7/symbol.png"
  },
  "EX Unseen Forces": {
    "logo": "https://images.pokemontcg.io/ex10/logo.png",
    "symbol": "https://images.pokemontcg.io/ex10/symbol.png"
  },
  "Emerging Powers": {
    "logo": "https://images.pokemontcg.io/bw2/logo.png",
    "symbol": "https://images.pokemontcg.io/bw2/symbol.png"
  },
  "Expedition": {
    "logo": "https://images.pokemontcg.io/ecard1/logo.png",
    "symbol": "https://images.pokemontcg.io/ecard1/symbol.png"
  },
  "Fossil": {
    "logo": "https://images.pokemontcg.io/base3/logo.png",
    "symbol": "https://images.pokemontcg.io/base3/symbol.png"
  },
  "Generations": {
    "logo": "https://images.pokemontcg.io/g1/logo.png",
    "symbol": "https://images.pokemontcg.io/g1/symbol.png"
  },
  "Generations: Radiant Collection": {
    "logo": "https://images.pokemontcg.io/g1/logo.png",
    "symbol": "https://images.pokemontcg.io/g1/symbol.png"
  },
  "Great Encounters": {
    "logo": "https://images.pokemontcg.io/dp4/logo.png",
    "symbol": "https://images.pokemontcg.io/dp4/symbol.png"
  },
  "Gym Challenge": {
    "logo": "https://images.pokemontcg.io/gym2/logo.png",
    "symbol": "https://images.pokemontcg.io/gym2/symbol.png"
  },
  "Gym Heroes": {
    "logo": "https://images.pokemontcg.io/gym1/logo.png",
    "symbol": "https://images.pokemontcg.io/gym1/symbol.png"
  },
  "HGSS Promos": {
    "logo": "https://images.pokemontcg.io/swshp/logo.png",
    "symbol": "https://images.pokemontcg.io/swshp/symbol.png"
  },
  "HeartGold SoulSilver": {
    "logo": "https://images.pokemontcg.io/hgss1/logo.png",
    "symbol": "https://images.pokemontcg.io/hgss1/symbol.png"
  },
  "Hidden Fates": {
    "logo": "https://images.pokemontcg.io/sm115/logo.png",
    "symbol": "https://images.pokemontcg.io/sm115/symbol.png"
  },
  "Hidden Fates: Shiny Vault": {
    "logo": "https://images.pokemontcg.io/sma/logo.png",
    "symbol": "https://images.pokemontcg.io/sma/symbol.png"
  },
  "Hidden Legends": {
    "logo": "https://images.pokemontcg.io/ex5/logo.png",
    "symbol": "https://images.pokemontcg.io/ex5/symbol.png"
  },
  "Jungle": {
    "logo": "https://images.pokemontcg.io/base2/logo.png",
    "symbol": "https://images.pokemontcg.io/base2/symbol.png"
  },
  "Kalos Starter Set": {
    "logo": "https://images.pokemontcg.io/xy0/logo.png",
    "symbol": "https://images.pokemontcg.io/xy0/symbol.png"
  },
  "Kids WB Promos": {
    "logo": "https://images.pokemontcg.io/basep/logo.png",
    "symbol": "https://images.pokemontcg.io/basep/symbol.png"
  },
  "Legendary Collection": {
    "logo": "https://images.pokemontcg.io/base6/logo.png",
    "symbol": "https://images.pokemontcg.io/base6/symbol.png"
  },
  "Legendary Treasures": {
    "logo": "https://images.pokemontcg.io/bw11/logo.png",
    "symbol": "https://images.pokemontcg.io/bw11/symbol.png"
  },
  "Legendary Treasures: Radiant Collection": {
    "logo": "https://images.pokemontcg.io/bw11/logo.png",
    "symbol": "https://images.pokemontcg.io/bw11/symbol.png"
  },
  "Legends Awakened": {
    "logo": "https://images.pokemontcg.io/dp6/logo.png",
    "symbol": "https://images.pokemontcg.io/dp6/symbol.png"
  },
  "ME01: Mega Evolution": {
    "logo": "https://images.pokemontcg.io/me1/logo.png",
    "symbol": "https://images.pokemontcg.io/me1/symbol.png"
  },
  "ME02: Phantasmal Flames": {
    "logo": "https://images.pokemontcg.io/me2/logo.png",
    "symbol": "https://images.pokemontcg.io/me2/symbol.png"
  },
  "ME03: Perfect Order": {
    "logo": "https://images.scrydex.com/pokemon/me3-logo/logo",
    "symbol": "https://images.scrydex.com/pokemon/me3-symbol/symbol"
  },
  "ME04: Chaos Rising": {
    "logo": "https://images.scrydex.com/pokemon/me4-logo/logo",
    "symbol": "https://images.scrydex.com/pokemon/me4-symbol/symbol"
  },
  "ME05: Pitch Black": {
    "logo": "https://images.scrydex.com/pokemon/me5-logo/logo",
    "symbol": "https://images.scrydex.com/pokemon/me5-symbol/symbol"
  },
  "ME: Ascended Heroes": {
    "logo": "https://images.scrydex.com/pokemon/me2pt5-logo/logo",
    "symbol": "https://images.scrydex.com/pokemon/me2pt5-symbol/symbol"
  },
  "Majestic Dawn": {
    "logo": "https://images.pokemontcg.io/dp5/logo.png",
    "symbol": "https://images.pokemontcg.io/dp5/symbol.png"
  },
  "Mysterious Treasures": {
    "logo": "https://images.pokemontcg.io/dp2/logo.png",
    "symbol": "https://images.pokemontcg.io/dp2/symbol.png"
  },
  "Neo Destiny": {
    "logo": "https://images.pokemontcg.io/neo4/logo.png",
    "symbol": "https://images.pokemontcg.io/neo4/symbol.png"
  },
  "Neo Discovery": {
    "logo": "https://images.pokemontcg.io/neo2/logo.png",
    "symbol": "https://images.pokemontcg.io/neo2/symbol.png"
  },
  "Neo Genesis": {
    "logo": "https://images.pokemontcg.io/neo1/logo.png",
    "symbol": "https://images.pokemontcg.io/neo1/symbol.png"
  },
  "Neo Revelation": {
    "logo": "https://images.pokemontcg.io/neo3/logo.png",
    "symbol": "https://images.pokemontcg.io/neo3/symbol.png"
  },
  "Next Destinies": {
    "logo": "https://images.pokemontcg.io/bw4/logo.png",
    "symbol": "https://images.pokemontcg.io/bw4/symbol.png"
  },
  "Nintendo Promos": {
    "logo": "https://images.pokemontcg.io/np/logo.png",
    "symbol": "https://images.pokemontcg.io/np/symbol.png"
  },
  "Noble Victories": {
    "logo": "https://images.pokemontcg.io/bw3/logo.png",
    "symbol": "https://images.pokemontcg.io/bw3/symbol.png"
  },
  "POP Series 1": {
    "logo": "https://images.pokemontcg.io/pop1/logo.png",
    "symbol": "https://images.pokemontcg.io/pop1/symbol.png"
  },
  "POP Series 2": {
    "logo": "https://images.pokemontcg.io/pop2/logo.png",
    "symbol": "https://images.pokemontcg.io/pop2/symbol.png"
  },
  "POP Series 3": {
    "logo": "https://images.pokemontcg.io/pop3/logo.png",
    "symbol": "https://images.pokemontcg.io/pop3/symbol.png"
  },
  "POP Series 4": {
    "logo": "https://images.pokemontcg.io/pop4/logo.png",
    "symbol": "https://images.pokemontcg.io/pop4/symbol.png"
  },
  "POP Series 5": {
    "logo": "https://images.pokemontcg.io/pop5/logo.png",
    "symbol": "https://images.pokemontcg.io/pop5/symbol.png"
  },
  "POP Series 6": {
    "logo": "https://images.pokemontcg.io/pop6/logo.png",
    "symbol": "https://images.pokemontcg.io/pop6/symbol.png"
  },
  "POP Series 7": {
    "logo": "https://images.pokemontcg.io/pop7/logo.png",
    "symbol": "https://images.pokemontcg.io/pop7/symbol.png"
  },
  "POP Series 8": {
    "logo": "https://images.pokemontcg.io/pop8/logo.png",
    "symbol": "https://images.pokemontcg.io/pop8/symbol.png"
  },
  "POP Series 9": {
    "logo": "https://images.pokemontcg.io/pop9/logo.png",
    "symbol": "https://images.pokemontcg.io/pop9/symbol.png"
  },
  "Plasma Blast": {
    "logo": "https://images.pokemontcg.io/bw10/logo.png",
    "symbol": "https://images.pokemontcg.io/bw10/symbol.png"
  },
  "Plasma Freeze": {
    "logo": "https://images.pokemontcg.io/bw9/logo.png",
    "symbol": "https://images.pokemontcg.io/bw9/symbol.png"
  },
  "Plasma Storm": {
    "logo": "https://images.pokemontcg.io/bw8/logo.png",
    "symbol": "https://images.pokemontcg.io/bw8/symbol.png"
  },
  "Platinum": {
    "logo": "https://images.pokemontcg.io/pl1/logo.png",
    "symbol": "https://images.pokemontcg.io/pl1/symbol.png"
  },
  "Pokemon GO": {
    "logo": "https://images.pokemontcg.io/pgo/logo.png",
    "symbol": "https://images.pokemontcg.io/pgo/symbol.png"
  },
  "Rising Rivals": {
    "logo": "https://images.pokemontcg.io/pl2/logo.png",
    "symbol": "https://images.pokemontcg.io/pl2/symbol.png"
  },
  "Rumble": {
    "logo": "https://images.pokemontcg.io/ru1/logo.png",
    "symbol": "https://images.pokemontcg.io/ru1/symbol.png"
  },
  "SM - Burning Shadows": {
    "logo": "https://images.pokemontcg.io/sm3/logo.png",
    "symbol": "https://images.pokemontcg.io/sm3/symbol.png"
  },
  "SM - Celestial Storm": {
    "logo": "https://images.pokemontcg.io/sm7/logo.png",
    "symbol": "https://images.pokemontcg.io/sm7/symbol.png"
  },
  "SM - Cosmic Eclipse": {
    "logo": "https://images.pokemontcg.io/sm12/logo.png",
    "symbol": "https://images.pokemontcg.io/sm12/symbol.png"
  },
  "SM - Crimson Invasion": {
    "logo": "https://images.pokemontcg.io/sm4/logo.png",
    "symbol": "https://images.pokemontcg.io/sm4/symbol.png"
  },
  "SM - Forbidden Light": {
    "logo": "https://images.pokemontcg.io/sm6/logo.png",
    "symbol": "https://images.pokemontcg.io/sm6/symbol.png"
  },
  "SM - Guardians Rising": {
    "logo": "https://images.pokemontcg.io/sm2/logo.png",
    "symbol": "https://images.pokemontcg.io/sm2/symbol.png"
  },
  "SM - Lost Thunder": {
    "logo": "https://images.pokemontcg.io/sm8/logo.png",
    "symbol": "https://images.pokemontcg.io/sm8/symbol.png"
  },
  "SM - Team Up": {
    "logo": "https://images.pokemontcg.io/sm9/logo.png",
    "symbol": "https://images.pokemontcg.io/sm9/symbol.png"
  },
  "SM - Ultra Prism": {
    "logo": "https://images.pokemontcg.io/sm5/logo.png",
    "symbol": "https://images.pokemontcg.io/sm5/symbol.png"
  },
  "SM - Unbroken Bonds": {
    "logo": "https://images.pokemontcg.io/sm10/logo.png",
    "symbol": "https://images.pokemontcg.io/sm10/symbol.png"
  },
  "SM - Unified Minds": {
    "logo": "https://images.pokemontcg.io/sm11/logo.png",
    "symbol": "https://images.pokemontcg.io/sm11/symbol.png"
  },
  "SM Base Set": {
    "logo": "https://images.pokemontcg.io/sm1/logo.png",
    "symbol": "https://images.pokemontcg.io/sm1/symbol.png"
  },
  "SM Promos": {
    "logo": "https://images.pokemontcg.io/swshp/logo.png",
    "symbol": "https://images.pokemontcg.io/swshp/symbol.png"
  },
  "SV01: Scarlet & Violet Base Set": {
    "logo": "https://images.pokemontcg.io/sv1/logo.png",
    "symbol": "https://images.pokemontcg.io/sv1/symbol.png"
  },
  "SV02: Paldea Evolved": {
    "logo": "https://images.pokemontcg.io/sv2/logo.png",
    "symbol": "https://images.pokemontcg.io/sv2/symbol.png"
  },
  "SV03: Obsidian Flames": {
    "logo": "https://images.pokemontcg.io/sv3/logo.png",
    "symbol": "https://images.pokemontcg.io/sv3/symbol.png"
  },
  "SV04: Paradox Rift": {
    "logo": "https://images.pokemontcg.io/sv4/logo.png",
    "symbol": "https://images.pokemontcg.io/sv4/symbol.png"
  },
  "SV05: Temporal Forces": {
    "logo": "https://images.pokemontcg.io/sv5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv5/symbol.png"
  },
  "SV06: Twilight Masquerade": {
    "logo": "https://images.pokemontcg.io/sv6/logo.png",
    "symbol": "https://images.pokemontcg.io/sv6/symbol.png"
  },
  "SV07: Stellar Crown": {
    "logo": "https://images.pokemontcg.io/sv7/logo.png",
    "symbol": "https://images.pokemontcg.io/sv7/symbol.png"
  },
  "SV08: Surging Sparks": {
    "logo": "https://images.pokemontcg.io/sv8/logo.png",
    "symbol": "https://images.pokemontcg.io/sv8/symbol.png"
  },
  "SV09: Journey Together": {
    "logo": "https://images.pokemontcg.io/sv9/logo.png",
    "symbol": "https://images.pokemontcg.io/sv9/symbol.png"
  },
  "SV10: Destined Rivals": {
    "logo": "https://images.pokemontcg.io/sv10/logo.png",
    "symbol": "https://images.pokemontcg.io/sv10/symbol.png"
  },
  "SV: Black Bolt": {
    "logo": "https://images.pokemontcg.io/zsv10pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/zsv10pt5/symbol.png"
  },
  "SV: Paldean Fates": {
    "logo": "https://images.pokemontcg.io/sv4pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv4pt5/symbol.png"
  },
  "SV: Prismatic Evolutions": {
    "logo": "https://images.pokemontcg.io/sv8pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv8pt5/symbol.png"
  },
  "SV: Scarlet & Violet 151": {
    "logo": "https://images.pokemontcg.io/sv3pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv3pt5/symbol.png"
  },
  "SV: Scarlet & Violet Promo Cards": {
    "logo": "https://images.pokemontcg.io/svp/logo.png",
    "symbol": "https://images.pokemontcg.io/svp/symbol.png"
  },
  "SV: Shrouded Fable": {
    "logo": "https://images.pokemontcg.io/sv6pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/sv6pt5/symbol.png"
  },
  "SV: White Flare": {
    "logo": "https://images.pokemontcg.io/rsv10pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/rsv10pt5/symbol.png"
  },
  "SWSH01: Sword & Shield Base Set": {
    "logo": "https://images.pokemontcg.io/swsh1/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh1/symbol.png"
  },
  "SWSH02: Rebel Clash": {
    "logo": "https://images.pokemontcg.io/swsh2/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh2/symbol.png"
  },
  "SWSH03: Darkness Ablaze": {
    "logo": "https://images.pokemontcg.io/swsh3/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh3/symbol.png"
  },
  "SWSH04: Vivid Voltage": {
    "logo": "https://images.pokemontcg.io/swsh4/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh4/symbol.png"
  },
  "SWSH05: Battle Styles": {
    "logo": "https://images.pokemontcg.io/swsh5/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh5/symbol.png"
  },
  "SWSH06: Chilling Reign": {
    "logo": "https://images.pokemontcg.io/swsh6/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh6/symbol.png"
  },
  "SWSH07: Evolving Skies": {
    "logo": "https://images.pokemontcg.io/swsh7/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh7/symbol.png"
  },
  "SWSH08: Fusion Strike": {
    "logo": "https://images.pokemontcg.io/swsh8/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh8/symbol.png"
  },
  "SWSH09: Brilliant Stars": {
    "logo": "https://images.pokemontcg.io/swsh9/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh9/symbol.png"
  },
  "SWSH09: Brilliant Stars Trainer Gallery": {
    "logo": "https://images.pokemontcg.io/swsh9tg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh9tg/symbol.png"
  },
  "SWSH10: Astral Radiance": {
    "logo": "https://images.pokemontcg.io/swsh10/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh10/symbol.png"
  },
  "SWSH10: Astral Radiance Trainer Gallery": {
    "logo": "https://images.pokemontcg.io/swsh10tg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh10tg/symbol.png"
  },
  "SWSH11: Lost Origin": {
    "logo": "https://images.pokemontcg.io/swsh11/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh11/symbol.png"
  },
  "SWSH11: Lost Origin Trainer Gallery": {
    "logo": "https://images.pokemontcg.io/swsh11tg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh11tg/symbol.png"
  },
  "SWSH12: Silver Tempest": {
    "logo": "https://images.pokemontcg.io/swsh12/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh12/symbol.png"
  },
  "SWSH12: Silver Tempest Trainer Gallery": {
    "logo": "https://images.pokemontcg.io/swsh12tg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh12tg/symbol.png"
  },
  "SWSH: Crown Zenith": {
    "logo": "https://images.pokemontcg.io/swsh12pt5/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh12pt5/symbol.png"
  },
  "SWSH: Crown Zenith: Galarian Gallery": {
    "logo": "https://images.pokemontcg.io/swsh12pt5gg/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh12pt5gg/symbol.png"
  },
  "SWSH: Sword & Shield Promo Cards": {
    "logo": "https://images.pokemontcg.io/swshp/logo.png",
    "symbol": "https://images.pokemontcg.io/swshp/symbol.png"
  },
  "Secret Wonders": {
    "logo": "https://images.pokemontcg.io/dp3/logo.png",
    "symbol": "https://images.pokemontcg.io/dp3/symbol.png"
  },
  "Shining Fates: Shiny Vault": {
    "logo": "https://images.pokemontcg.io/swsh45sv/logo.png",
    "symbol": "https://images.pokemontcg.io/swsh45sv/symbol.png"
  },
  "Shining Legends": {
    "logo": "https://images.pokemontcg.io/sm35/logo.png",
    "symbol": "https://images.pokemontcg.io/sm35/symbol.png"
  },
  "Skyridge": {
    "logo": "https://images.pokemontcg.io/ecard3/logo.png",
    "symbol": "https://images.pokemontcg.io/ecard3/symbol.png"
  },
  "Southern Islands": {
    "logo": "https://images.pokemontcg.io/si1/logo.png",
    "symbol": "https://images.pokemontcg.io/si1/symbol.png"
  },
  "Stormfront": {
    "logo": "https://images.pokemontcg.io/dp7/logo.png",
    "symbol": "https://images.pokemontcg.io/dp7/symbol.png"
  },
  "Supreme Victors": {
    "logo": "https://images.pokemontcg.io/pl3/logo.png",
    "symbol": "https://images.pokemontcg.io/pl3/symbol.png"
  },
  "Team Rocket": {
    "logo": "https://images.pokemontcg.io/base5/logo.png",
    "symbol": "https://images.pokemontcg.io/base5/symbol.png"
  },
  "Triumphant": {
    "logo": "https://images.pokemontcg.io/hgss4/logo.png",
    "symbol": "https://images.pokemontcg.io/hgss4/symbol.png"
  },
  "Undaunted": {
    "logo": "https://images.pokemontcg.io/hgss3/logo.png",
    "symbol": "https://images.pokemontcg.io/hgss3/symbol.png"
  },
  "Unleashed": {
    "logo": "https://images.pokemontcg.io/hgss2/logo.png",
    "symbol": "https://images.pokemontcg.io/hgss2/symbol.png"
  },
  "WoTC Promo": {
    "logo": "https://images.pokemontcg.io/basep/logo.png",
    "symbol": "https://images.pokemontcg.io/basep/symbol.png"
  },
  "XY - Ancient Origins": {
    "logo": "https://images.pokemontcg.io/xy7/logo.png",
    "symbol": "https://images.pokemontcg.io/xy7/symbol.png"
  },
  "XY - BREAKpoint": {
    "logo": "https://images.pokemontcg.io/xy9/logo.png",
    "symbol": "https://images.pokemontcg.io/xy9/symbol.png"
  },
  "XY - BREAKthrough": {
    "logo": "https://images.pokemontcg.io/xy8/logo.png",
    "symbol": "https://images.pokemontcg.io/xy8/symbol.png"
  },
  "XY - Evolutions": {
    "logo": "https://images.pokemontcg.io/xy12/logo.png",
    "symbol": "https://images.pokemontcg.io/xy12/symbol.png"
  },
  "XY - Fates Collide": {
    "logo": "https://images.pokemontcg.io/xy10/logo.png",
    "symbol": "https://images.pokemontcg.io/xy10/symbol.png"
  },
  "XY - Flashfire": {
    "logo": "https://images.pokemontcg.io/xy2/logo.png",
    "symbol": "https://images.pokemontcg.io/xy2/symbol.png"
  },
  "XY - Furious Fists": {
    "logo": "https://images.pokemontcg.io/xy3/logo.png",
    "symbol": "https://images.pokemontcg.io/xy3/symbol.png"
  },
  "XY - Phantom Forces": {
    "logo": "https://images.pokemontcg.io/xy4/logo.png",
    "symbol": "https://images.pokemontcg.io/xy4/symbol.png"
  },
  "XY - Primal Clash": {
    "logo": "https://images.pokemontcg.io/xy5/logo.png",
    "symbol": "https://images.pokemontcg.io/xy5/symbol.png"
  },
  "XY - Roaring Skies": {
    "logo": "https://images.pokemontcg.io/xy6/logo.png",
    "symbol": "https://images.pokemontcg.io/xy6/symbol.png"
  },
  "XY - Steam Siege": {
    "logo": "https://images.pokemontcg.io/xy11/logo.png",
    "symbol": "https://images.pokemontcg.io/xy11/symbol.png"
  },
  "XY Base Set": {
    "logo": "https://images.pokemontcg.io/xy1/logo.png",
    "symbol": "https://images.pokemontcg.io/xy1/symbol.png"
  },
  "XY Promos": {
    "logo": "https://images.pokemontcg.io/swshp/logo.png",
    "symbol": "https://images.pokemontcg.io/swshp/symbol.png"
  }
};

module.exports = { SET_IMAGES };
