#!/usr/bin/env node
// Generates lib/reprintPrintings.js from the catalogue.
//
//   node scripts/seo/generateReprintPrintings.mjs          # print a summary
//   node scripts/seo/generateReprintPrintings.mjs --write   # write the file
//
// WHY a generated file rather than a lookup: lib/dealQuality.js is pure
// and client-safe and runs on every render, so it cannot query the
// catalogue. Without this data it can only ask "does the title mention a
// reprint set", which cannot tell a genuine vintage card with "30th"
// stuffed in for search traffic from a real reprint ambiguity. With it,
// the question becomes the right one: does the reprint set actually
// contain this card at this number?
//
// Re-run when a reprint set is added or renumbered. Read-only against the
// catalogue; the only thing it writes is the lib file, and only with
// --write.
import { existsSync, writeFileSync } from "node:fs";
import { config as loadDotenv } from "dotenv";
import { createClient } from "@supabase/supabase-js";

if (existsSync(".env.local")) loadDotenv({ path: ".env.local", quiet: true });
const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false },
});

// Keys must match lib/dealQuality REPRINT_FAMILIES.
const FAMILIES = [
  { key: "30th", set: /\b30th\b/i },
  { key: "celebrations", set: /\bcelebrations\b/i },
];

// Names vary in punctuation between a listing and the catalogue
// ("Mewtwo-EX" vs "Mewtwo EX"), so compare on letters and digits only.
const normName = (s) => String(s ?? "").toLowerCase().replace(/[^a-z0-9]+/g, "");
const normNum = (s) =>
  String(s ?? "")
    .split("/")
    .map((p) => p.trim().replace(/^0+(?=\d)/, ""))
    .join("/");

const rows = [];
for (let from = 0; ; from += 1000) {
  const { data, error } = await db.from("card_catalog").select("*").order("tcgplayer_id", { ascending: true }).range(from, from + 999);
  if (error) throw new Error(error.message);
  rows.push(...(data ?? []));
  if ((data?.length ?? 0) < 1000) break;
}

const out = {};
for (const fam of FAMILIES) {
  const inFam = rows.filter((r) => fam.set.test(String(r.set ?? "")));
  // number -> the names the family prints at that number. Number alone is
  // not enough (the 30th set has a card at 18/132 and so does Gym Heroes),
  // and exact name equality is too strict: a deal row says "Metagross"
  // where the catalogue says "Metagross Delta Species". So the names are
  // kept per number and compared by prefix at lookup time.
  const index = {};
  for (const r of inFam) {
    const num = normNum(r.card_number);
    const nm = normName(r.name);
    if (!num || !nm) continue;
    (index[num] ??= []).push(nm);
  }
  for (const k of Object.keys(index)) index[k] = [...new Set(index[k])].sort();
  out[fam.key] = index;
  console.log(
    `  ${fam.key.padEnd(14)} ${String(inFam.length).padStart(4)} catalogue cards, ${Object.keys(index).length} numbers`
  );
}

if (!process.argv.includes("--write")) {
  console.log("\n  (dry run - pass --write to update lib/reprintPrintings.js)");
  process.exit(0);
}

const body = `// GENERATED by scripts/seo/generateReprintPrintings.mjs - do not hand-edit.
// Re-run that script when a reprint set is added or renumbered.
//
// Reprint sets keep the ORIGINAL card's number (Celebrations: Classic
// Collection carries Blastoise at 2/102, the Base Set number). That makes
// the number useless for telling an original from a reprint - but only
// for the numbers the reprint set actually uses. These lists are what let
// lib/dealQuality separate a real ambiguity from a seller stuffing "30th"
// into the title of a genuine vintage card.
//
// Generated ${new Date().toISOString().slice(0, 10)} from card_catalog.
// Keys are quoted: "30th" is not a valid bare identifier.
const REPRINT_CARDS = ${JSON.stringify(out, null, 2)};

// Letters and digits only, so "Mewtwo-EX" and "Mewtwo EX" agree.
function normaliseCardName(value) {
  return String(value ?? "").toLowerCase().replace(/[^a-z0-9]+/g, "");
}

// "12/113" -> "12/113" with leading zeros stripped from each part.
function normaliseCardNumber(value) {
  return String(value ?? "")
    .split("/")
    .map((part) => part.trim().replace(/^0+(?=\\d)/, ""))
    .join("/");
}

// Does this reprint family contain THIS card at THIS number? Both must
// match: the family having some card at 18/132 says nothing about a
// listing for Misty 18/132.
// Names are compared by PREFIX in either direction, because a deal row
// carries "Metagross" where the catalogue carries "Metagross Delta
// Species". Exact equality would miss every such pair and report a real
// ambiguity as keyword stuffing.
function reprintFamilyHasCard(family, name, number) {
  const index = REPRINT_CARDS[family];
  if (!index) return false;
  const n = normaliseCardNumber(number);
  const nm = normaliseCardName(name);
  if (n === "" || nm === "") return false;
  const names = index[n];
  if (!names) return false;
  return names.some((catalogueName) => catalogueName.startsWith(nm) || nm.startsWith(catalogueName));
}

module.exports = { REPRINT_CARDS, normaliseCardName, normaliseCardNumber, reprintFamilyHasCard };
`;
writeFileSync("lib/reprintPrintings.js", body);
console.log("\n  wrote lib/reprintPrintings.js");
