// Run with: node scripts/generatePokemonSpecies.js
//
// One-off generator for lib/pokemonSpeciesData.js - the canonical National
// Pokedex species display-name whitelist that lib/pokemonSpecies.js's
// extractSpecies() matches watchlist card names against (Phase 5 -
// /pokemon/[slug] species entity pages).
//
// Pulls every species from PokeAPI in National Dex order and takes each
// one's official English display name (names[].name where language is
// "en") - this is what gives the correct punctuation/casing for the
// awkward ones: "Mr. Mime", "Farfetch'd", "Ho-Oh", "Type: Null",
// "Porygon-Z", "Tapu Koko", "Nidoran♀", "Flabebe", the paradox names, etc.
//
// No API key, no DB. Overwrites lib/pokemonSpeciesData.js. Re-run whenever
// a new generation is released.

const fs = require("fs");
const path = require("path");

const LIST_URL = "https://pokeapi.co/api/v2/pokemon-species?limit=100000&offset=0";
const CONCURRENCY = 24;
const OUT_PATH = path.join(__dirname, "..", "lib", "pokemonSpeciesData.js");

async function getJson(url) {
  for (let attempt = 1; attempt <= 4; attempt++) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      return await res.json();
    } catch (err) {
      if (attempt === 4) throw err;
      await new Promise((r) => setTimeout(r, 400 * attempt));
    }
  }
}

async function mapPool(items, worker, concurrency) {
  const results = new Array(items.length);
  let next = 0;
  async function run() {
    while (next < items.length) {
      const i = next++;
      results[i] = await worker(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: concurrency }, run));
  return results;
}

async function main() {
  console.log("Fetching species index...");
  const { results: index } = await getJson(LIST_URL);
  console.log(`  ${index.length} species entries`);

  let done = 0;
  const entries = await mapPool(
    index,
    async (entry) => {
      const data = await getJson(entry.url);
      const en = data.names.find((n) => n.language.name === "en");
      done++;
      if (done % 100 === 0) console.log(`  ${done}/${index.length}`);
      return { id: data.id, name: en ? en.name : data.name };
    },
    CONCURRENCY
  );

  // National Dex order. Ids above ~10000 are alternate forms living under
  // /pokemon, not /pokemon-species, so in practice every entry here is a
  // real dex species - sort by id and keep them all.
  entries.sort((a, b) => a.id - b.id);

  const names = entries.map((e) => e.name);
  const unique = [...new Set(names)];
  if (unique.length !== names.length) {
    console.warn(`  WARNING: ${names.length - unique.length} duplicate name(s) collapsed`);
  }

  const body =
    "// AUTO-GENERATED by scripts/generatePokemonSpecies.js - do not edit by hand.\n" +
    "// Canonical National Pokedex species display names (English), in dex order.\n" +
    "// Source: PokeAPI (https://pokeapi.co/). Regenerate: node scripts/generatePokemonSpecies.js\n" +
    `// ${unique.length} species as of ${new Date().toISOString().slice(0, 10)}.\n\n` +
    "const SPECIES = [\n" +
    unique.map((n) => `  ${JSON.stringify(n)},`).join("\n") +
    "\n];\n\nmodule.exports = { SPECIES };\n";

  fs.writeFileSync(OUT_PATH, body);
  console.log(`\nWrote ${unique.length} species to ${OUT_PATH}`);
}

main().catch((err) => {
  console.error(err.message);
  process.exit(1);
});
