// GENERATED by scripts/seo/buildSurvivalAggregate.mjs - do not edit by hand.
// A FIXED, DATED SNAPSHOT of listing-disappearance figures. Aggregates
// only: no listing ids, no seller fields, no URLs.
//
// Read the `limits` array before using any number here. In particular:
// absence from a search is NOT a sale.
export const LISTING_DISAPPEARANCE = Object.freeze({
  "version": "2026-09-20.1",
  "id": "listing-disappearance-2026-09",
  "window": {
    "start": "2026-08-26",
    "end": "2026-09-20",
    "days": 25
  },
  "method": {
    "unit": "one below-market eBay listing as first found by our scanner",
    "resolvedBy": "a later confirmed run of the SAME search (watchlist), so absence is evidence about the listing rather than about our coverage",
    "excludes": "listings we withheld ourselves, listings still live, and listings first seen on day one (unknown age)"
  },
  "population": {
    "rowsConsidered": 31889,
    "excludedHeldByUs": 7624,
    "excludedStillActive": 1361,
    "excludedFirstDay": 4686,
    "candidates": 18218,
    "excludedNeverReSearched": 3071,
    "measured": 15147,
    "measuredShareOfCandidates": 83.1
  },
  "headline": {
    "goneByNextScan": 11794,
    "goneByNextScanPct": 77.9,
    "medianGapToNextScanDays": 1.2,
    "reSeenAtLeastOnce": 3353,
    "reSeenMedianObservedDays": 1.8
  },
  "byReferenceBand": {
    "under $25": {
      "records": 3584,
      "goneByNextScanPct": 80.1,
      "reSeenMedianDays": 1.1
    },
    "$25 to $100": {
      "records": 7910,
      "goneByNextScanPct": 79.9,
      "reSeenMedianDays": 1.6
    },
    "$100 or more": {
      "records": 3653,
      "goneByNextScanPct": 71.3,
      "reSeenMedianDays": 2.2
    }
  },
  "limits": [
    "Absence from a search is not a sale. A listing also leaves when it ends, is cancelled, is relisted, or changes price enough to fall outside the below-market filter.",
    "No sell-through rate, time-to-sale or market size can be derived from this.",
    "Resolution is limited by how often each search runs: the finding is 'gone by the next run', not an exact moment.",
    "Listings first seen on day one are excluded because their age at discovery is unknown."
  ]
});
